apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: command-center
  labels:
    app: api
    app.kubernetes.io/part-of: command-center
spec:
  type: ClusterIP
  selector:
    app: api
  ports:
    - port: 80
      targetPort: 3001
      protocol: TCP
