apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: command-center
  labels:
    app: web
    app.kubernetes.io/part-of: command-center
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
